Yd chat merged
GreeneOcean/Project_Greene pull request #12
Opened 2022-05-10 19:57 UTC by dybn7758

Please ......

2022-05-10 23:30 UTC, 7socks requested changes
1. Change onKeyPress to onKeyDown
2. Look into unicode for displaying emojis reliably

2022-05-10 23:30 UTC, 7socks commented on client/src/App.jsx
> +
Thinking that this might look cleaner if the http address was imported from process.env or a hidden config file. Not a big priority.

2022-05-10 23:30 UTC, 7socks commented on client/src/Chat/Chat.js
> +            event.key === "Enter" && sendMessage();
Keypress is deprecated in current html. Replace with onKeyDown.

2022-05-10 23:30 UTC, 7socks commented on server/index.js
> +  socket.on("send_message", (data) => {
I like the emoji, might be safer to use its unicode code if possible. If you don't have time to implement this, don't worry about it!

2022-05-10 23:30 UTC, 7socks commented on server/index.js
> +  });
I'm guessing this is an emoji on line 30. It's not displaying for me, so be aware of this.

2022-05-10 23:39 UTC, positivefx requested changes

2022-05-10 23:39 UTC, positivefx commented on client/src/Chat/Chat.js
> +function Chat({ socket, username, room }) {
Do you need the room? It doesnt seem to be used.

2022-05-11 23:38 UTC, positivefx approved these changes

2022-05-11 23:40 UTC, 7socks approved these changes

2022-05-11 23:42 UTC, merged