CGF merge #1
GreeneOcean/Project_Greene pull request #9
Opened 2022-05-10 19:30 UTC by cgf5033

nav bar + login / signin added

2022-05-10 19:50 UTC, positivefx approved these changes

2022-05-10 19:52 UTC, cgf5033 commented
I like to merge

2022-05-10 19:55 UTC, Doobss approved these changes

2022-05-10 22:28 UTC, 7socks requested changes

2022-05-10 22:28 UTC, 7socks commented on .vscode/settings.json
> +}
please remove this file

2022-05-10 22:28 UTC, 7socks commented on client/src/Nav/components/Search.js
> +          }}
remove commented lines unless you will need them later

2022-05-11 10:37 UTC, Doobss commented on client/src/Auth/Auth.js
> +  const [loggedIn, setLoggedIn] = useState(false);
@cgf5033 assuming "const [loggedIn, setLoggedIn] = useState(false);" is just here to be used later when auth api is set up, just want to confirm.

2022-05-11 10:39 UTC, Doobss commented on client/src/Auth/Auth.js
> +
@cgf5033 "ButtonSM" doesn't seemed to be used in this file and its not exported so it seems to be not needed. If so I would think it should be removed.

2022-05-11 10:41 UTC, Doobss commented on client/src/Auth/components/Login.js
> +          value={userText}
@cgf5033 instead of styling the input inline maybe offloading it to a styled component (styled.input`...`) so it can be reused and is a but cleaner.

2022-05-11 10:46 UTC, Doobss commented on client/src/Auth/components/SignUp.js
> +
@cgf5033 seeing all of these inputs with the same requirements and internal state make me wonder if we can offload the functionality into a separate and reusable component. Not super high on the docket though.

2022-05-11 10:51 UTC, Doobss commented on client/src/Auth/components/SignUp.js
> +
@cgf5033 "ButtonSM" has being defined multiple times isnt ideal, I would assume this is just a product of early stage development. Still having either a single file with this component or making a single file for the whole auth component where "ButtonSM" is defined once could be a solution. I'd like to hear your thoughts.

2022-05-11 10:53 UTC, Doobss approved these changes, later dismissed
No immediate change requests other than what Elfric has already asked.

2022-05-11 10:56 UTC, Doobss reviewed
Lol didn't see Steph had approved already. Just wanted to let Elfric have the final say

2022-05-11 12:41 UTC, closed without merging